import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useRef } from 'react';
import Webcam from 'react-webcam';

const Home: NextPage = () => {
  const webcamRef = useRef(null);
  const videoConstraints: MediaTrackConstraints = {
    width: { min: 720, ideal: 1920, max: 1920 },
    height: { min: 540, ideal: 1080 },
    facingMode: 'user',
    aspectRatio: 1.777777778,
    frameRate: { max: 30 },
  };

  useEffect(() => {
    if (webcamRef) console.log(webcamRef);
  }, [webcamRef]);

  return (
    <div className="w-full h-screen flex">
      <Head>
        <title>鬼畜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Webcam
        className="m-auto invisible"
        forceScreenshotSourceSize
        mirrored={true}
        ref={webcamRef}
        screenshotFormat="image/jpeg"
        videoConstraints={videoConstraints}
      />
    </div>
  );
};

export default Home;
