/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import {
  CSSProperties,
  MutableRefObject,
  useEffect,
  useRef,
  useState,
} from 'react';
import Webcam from 'react-webcam';

const Home: NextPage = () => {
  const [started, setStarted] = useState(false);
  const [imgSrc, setImgSrc] = useState('');

  const timerRef = useRef<NodeJS.Timer>();
  const webcamRef: MutableRefObject<any> = useRef(null);

  const videoConstraints: MediaTrackConstraints = {
    width: { min: 720, ideal: 1920, max: 1920 },
    height: { min: 540, ideal: 1080 },
    facingMode: 'user',
    aspectRatio: 1.777777778,
    frameRate: { max: 30 },
  };

  const handleOnClick = () => {
    if (started) {
      clearTimeout(timerRef.current!);
      setStarted(false);
    } else {
      const img = webcamRef.current.getScreenshot();
      setImgSrc(img);
      setStarted(true);

      timerRef.current = setInterval(() => {
        const img = webcamRef.current.getScreenshot();
        setTimeout(() => {
          console.log(new Date().getTime);
          setImgSrc(img);
        }, Math.random() * 3000);
      }, 100);
    }
  };

  useEffect(() => {
    const video = document.getElementsByTagName('video')[0];
    const { x, y } = video.getBoundingClientRect();
    const img = document.getElementsByTagName('img')[0];
    if (img) img.setAttribute('style', `left: ${x}px; top: ${y}px;`);
  }, [webcamRef, started]);

  return (
    <div className="w-full h-screen flex flex-col">
      <Head>
        <title>鬼畜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {started ? <img className="absolute" src={imgSrc} alt="" /> : null}

      <Webcam
        className={`m-auto ${started ? 'invisible' : ''}`}
        forceScreenshotSourceSize
        mirrored={true}
        ref={webcamRef}
        screenshotFormat="image/jpeg"
        videoConstraints={videoConstraints}
      />

      <button
        className="w-28 h-10 rounded-lg text-white m-auto mt-0 bg-indigo-600"
        onClick={handleOnClick}
      >
        {started ? '停一停' : '开始鬼畜'}
      </button>
    </div>
  );
};

export default Home;
